/**
 * 宁波市租房示例数据
 * ==================
 * 覆盖 6 个区，共 12 条房源
 *
 * 数据说明：
 * - prices: 按朝向+楼层列出所有不同价格。只要价格不同就单独列一行
 * - appliances: 每个电器的能耗等级(1-5)和开一天的花费
 * - utilities: 物业费/网费/停车费，标注是否含在租金内
 * - reviews: 用户评价，按星级自动分好评(≥4星)和差评(≤2星)
 */

const MOCK_LISTINGS = [
  {
    id: 'mock-001',
    title: '测试1',
    address: '海曙区翠柏路168号翠柏一里12幢',
    district: '海曙区',
    lat: 29.872,
    lng: 121.535,
    area_sqm: 85,
    bedrooms: 2,
    halls: 1,
    description: '翠柏一里位于海曙核心地段，小区环境整洁。步行5分钟到地铁1号线大卿桥站，周边有欧尚超市、宁波市中医院。全明户型，南北通透，精装修，拎包入住。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 3, monthly_rent: 2500 },
      { orientation: '南', floor_level: '中层', floor_number: 12, monthly_rent: 3000 },
      { orientation: '南', floor_level: '高层', floor_number: 22, monthly_rent: 3200 },
      { orientation: '北', floor_level: '低层', floor_number: 3, monthly_rent: 2200 },
      { orientation: '北', floor_level: '中层', floor_number: 12, monthly_rent: 2600 },
      { orientation: '东', floor_level: '中层', floor_number: 12, monthly_rent: 2800 },
      { orientation: '西', floor_level: '中层', floor_number: 12, monthly_rent: 2700 },
    ],
    utilities: {
      water_price: 3.5,
      electricity_price: 0.6,
      appliances: [
        { name: '空调（卧室）', energy_level: 3, power_watts: 1200, daily_cost_yuan: 7.2 },
        { name: '空调（客厅）', energy_level: 4, power_watts: 2000, daily_cost_yuan: 14.4 },
        { name: '热水器', energy_level: 2, power_watts: 2000, daily_cost_yuan: 3.6 },
        { name: '冰箱', energy_level: 1, power_watts: 100, daily_cost_yuan: 1.2 },
        { name: '洗衣机', energy_level: 2, power_watts: 500, daily_cost_yuan: 1.8 },
      ],
      property_fee: 150,
      property_fee_included: false,
      internet_fee: 50,
      internet_fee_included: true,
      parking_fee: 200,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r1', user_name: '小明', rating: 5, content: '房东人超好，维修响应很快。小区楼下就是菜市场，买菜太方便了！', created_at: '2024-07-15' },
      { id: 'r2', user_name: '小红', rating: 4, content: '交通确实方便，地铁走路5分钟。房子采光也不错。', created_at: '2024-07-10' },
      { id: 'r3', user_name: '小刚', rating: 5, content: '住了半年了，邻居都很安静，物业管理也规范。', created_at: '2024-06-28' },
      { id: 'r4', user_name: '阿芳', rating: 2, content: '老小区停车位太少了，晚上回来经常找不到车位。', created_at: '2024-06-20' },
      { id: 'r5', user_name: '大刘', rating: 1, content: '夏天西晒房间很热，客厅空调能耗太高，一个月电费300多。', created_at: '2024-06-15' },
      { id: 'r6', user_name: '静静', rating: 5, content: '周边生活配套齐全，超市医院都在步行范围内。推荐！', created_at: '2024-05-30' },
      { id: 'r7', user_name: '老陈', rating: 3, content: '整体还行，就是装修有点旧了，不过价格确实实惠。', created_at: '2024-05-20' },
      { id: 'r8', user_name: '小李', rating: 5, content: '首次租房就遇到好房东，很幸运。小区绿化也好。', created_at: '2024-05-10' },
    ]
  },

  {
    id: 'mock-002',
    title: '测试2',
    address: '海曙区府桥街35号',
    district: '海曙区',
    lat: 29.868,
    lng: 121.545,
    area_sqm: 50,
    bedrooms: 1,
    halls: 1,
    description: '鼓楼核心地段，下楼就是步行街。适合年轻人居住，周边餐饮娱乐丰富。一室一厅格局，带独立厨卫。距离地铁2号线鼓楼站步行3分钟。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 2, monthly_rent: 2200 },
      { orientation: '南', floor_level: '中层', floor_number: 8, monthly_rent: 2500 },
      { orientation: '南', floor_level: '高层', floor_number: 18, monthly_rent: 2800 },
      { orientation: '北', floor_level: '低层', floor_number: 2, monthly_rent: 1900 },
      { orientation: '北', floor_level: '中层', floor_number: 8, monthly_rent: 2200 },
    ],
    utilities: {
      water_price: 3.5,
      electricity_price: 0.6,
      appliances: [
        { name: '空调', energy_level: 2, power_watts: 1000, daily_cost_yuan: 4.8 },
        { name: '热水器', energy_level: 1, power_watts: 1500, daily_cost_yuan: 2.4 },
        { name: '冰箱', energy_level: 1, power_watts: 80, daily_cost_yuan: 0.96 },
        { name: '洗衣机', energy_level: 3, power_watts: 400, daily_cost_yuan: 2.0 },
      ],
      property_fee: 80,
      property_fee_included: true,
      internet_fee: 50,
      internet_fee_included: false,
      parking_fee: 0,
      parking_fee_included: true,
    },
    reviews: [
      { id: 'r9', user_name: '小美', rating: 5, content: '位置绝了！下楼就是鼓楼，吃的玩的多得不得了。', created_at: '2024-07-12' },
      { id: 'r10', user_name: '阿强', rating: 4, content: '房子小但布置合理，一个人住刚刚好。房东阿姨很热心。', created_at: '2024-07-05' },
      { id: 'r11', user_name: '文文', rating: 1, content: '楼下太吵了，周末晚上根本没法早睡。不适合需要安静的人。', created_at: '2024-06-25' },
      { id: 'r12', user_name: '大伟', rating: 5, content: '物业费已经包在房租里了，省心。没有停车位但对我不影响。', created_at: '2024-06-18' },
    ]
  },

  {
    id: 'mock-003',
    title: '测试3',
    address: '鄞州区四明中路518号都市森林',
    district: '鄞州区',
    lat: 29.808,
    lng: 121.568,
    area_sqm: 130,
    bedrooms: 3,
    halls: 2,
    description: '鄞州万达步行可达，都市森林高档小区。三室两厅两卫，全明户型，精装修。小区有游泳池、健身房。离宁波博物馆、鄞州公园也很近。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 5, monthly_rent: 5500 },
      { orientation: '南', floor_level: '中层', floor_number: 15, monthly_rent: 6200 },
      { orientation: '南', floor_level: '高层', floor_number: 28, monthly_rent: 6800 },
      { orientation: '东南', floor_level: '中层', floor_number: 15, monthly_rent: 6000 },
      { orientation: '西南', floor_level: '中层', floor_number: 15, monthly_rent: 5800 },
    ],
    utilities: {
      water_price: 3.8,
      electricity_price: 0.62,
      appliances: [
        { name: '中央空调', energy_level: 1, power_watts: 3500, daily_cost_yuan: 17.0 },
        { name: '热水器', energy_level: 1, power_watts: 2500, daily_cost_yuan: 3.0 },
        { name: '冰箱（双开门）', energy_level: 1, power_watts: 150, daily_cost_yuan: 1.8 },
        { name: '洗衣机', energy_level: 1, power_watts: 600, daily_cost_yuan: 2.0 },
        { name: '洗碗机', energy_level: 2, power_watts: 1800, daily_cost_yuan: 4.5 },
      ],
      property_fee: 520,
      property_fee_included: false,
      internet_fee: 80,
      internet_fee_included: false,
      parking_fee: 350,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r13', user_name: '老周', rating: 5, content: '小区环境一流，物业服务到位。虽然物业费贵但值这个钱。', created_at: '2024-07-18' },
      { id: 'r14', user_name: '莉莉', rating: 4, content: '房子采光无敌好，每个房间都有阳光。装修也好。', created_at: '2024-07-08' },
      { id: 'r15', user_name: '阿杰', rating: 5, content: '中央空调一级能耗确实省电，夏天全天开电费也没想象中高。', created_at: '2024-06-30' },
      { id: 'r16', user_name: '小陈', rating: 2, content: '停车费350一个月有点贵了，而且地下车位还要排队。', created_at: '2024-06-22' },
      { id: 'r17', user_name: '大鹏', rating: 5, content: '万达就在楼下，生活太方便了。小区游泳池夏天开放，很棒。', created_at: '2024-06-15' },
      { id: 'r18', user_name: '阿琳', rating: 3, content: '整体不错但网费要自己出，而且物业费也不便宜。总成本比想象中高。', created_at: '2024-06-01' },
    ]
  },

  {
    id: 'mock-004',
    title: '测试4',
    address: '鄞州区天童南路568号',
    district: '鄞州区',
    lat: 29.805,
    lng: 121.550,
    area_sqm: 40,
    bedrooms: 1,
    halls: 0,
    description: '南部商务区青年公寓，精装单间带独卫。适合在南部商务区上班的年轻人。楼下有便利店、餐厅。免费WiFi覆盖。共享厨房在每层公共区域。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 3, monthly_rent: 1800 },
      { orientation: '南', floor_level: '中层', floor_number: 10, monthly_rent: 2000 },
      { orientation: '南', floor_level: '高层', floor_number: 20, monthly_rent: 2200 },
      { orientation: '北', floor_level: '低层', floor_number: 3, monthly_rent: 1600 },
      { orientation: '北', floor_level: '中层', floor_number: 10, monthly_rent: 1800 },
      { orientation: '东', floor_level: '中层', floor_number: 10, monthly_rent: 1950 },
    ],
    utilities: {
      water_price: 3.5,
      electricity_price: 0.6,
      appliances: [
        { name: '空调', energy_level: 3, power_watts: 1000, daily_cost_yuan: 6.0 },
        { name: '热水器', energy_level: 2, power_watts: 1500, daily_cost_yuan: 2.8 },
        { name: '小冰箱', energy_level: 2, power_watts: 70, daily_cost_yuan: 0.85 },
      ],
      property_fee: 0,
      property_fee_included: true,
      internet_fee: 30,
      internet_fee_included: true,
      parking_fee: 0,
      parking_fee_included: true,
    },
    reviews: [
      { id: 'r19', user_name: '小吴', rating: 5, content: '上班走路10分钟，太幸福了。公寓管理也很好。', created_at: '2024-07-20' },
      { id: 'r20', user_name: '阿珍', rating: 4, content: '一个人住刚刚好，麻雀虽小五脏俱全。', created_at: '2024-07-14' },
      { id: 'r21', user_name: '小马', rating: 1, content: '隔音太差了，隔壁说话都能听到。共享厨房也经常有人不收拾。', created_at: '2024-07-05' },
      { id: 'r22', user_name: '大林', rating: 2, content: '没有洗衣机要手洗衣服，太麻烦了。夏天电费也高。', created_at: '2024-06-28' },
    ]
  },

  {
    id: 'mock-005',
    title: '测试5',
    address: '江北区老外滩中马路128号',
    district: '江北区',
    lat: 29.882,
    lng: 121.556,
    area_sqm: 160,
    bedrooms: 3,
    halls: 2,
    description: '老外滩一线江景房，大平层设计，客厅就能看到三江口夜景。豪华装修，全屋智能家居。步行到老外滩酒吧街2分钟，来福士广场步行8分钟。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '中层', floor_number: 16, monthly_rent: 8500 },
      { orientation: '南', floor_level: '高层', floor_number: 30, monthly_rent: 9500 },
      { orientation: '东南', floor_level: '高层', floor_number: 30, monthly_rent: 10000 },
    ],
    utilities: {
      water_price: 3.8,
      electricity_price: 0.62,
      appliances: [
        { name: '中央空调', energy_level: 1, power_watts: 5000, daily_cost_yuan: 24.0 },
        { name: '热水器', energy_level: 1, power_watts: 3000, daily_cost_yuan: 3.6 },
        { name: '冰箱（双开门）', energy_level: 1, power_watts: 200, daily_cost_yuan: 2.4 },
        { name: '洗衣机+烘干机', energy_level: 1, power_watts: 1500, daily_cost_yuan: 3.0 },
        { name: '洗碗机', energy_level: 1, power_watts: 1800, daily_cost_yuan: 3.6 },
        { name: '烤箱', energy_level: 2, power_watts: 2500, daily_cost_yuan: 5.0 },
      ],
      property_fee: 800,
      property_fee_included: false,
      internet_fee: 100,
      internet_fee_included: false,
      parking_fee: 400,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r23', user_name: '富豪张', rating: 5, content: '江景绝了！每晚回家看到三江口夜景，一天的疲惫都没了。', created_at: '2024-07-22' },
      { id: 'r24', user_name: 'Lisa', rating: 4, content: '装修品味好，全屋智能也很方便。就是物业费加停车费一个月要1200。', created_at: '2024-07-15' },
      { id: 'r25', user_name: '王总', rating: 5, content: '值这个价。老外滩核心地段，接待客户也有面子。', created_at: '2024-06-30' },
      { id: 'r26', user_name: '小赵', rating: 1, content: '晚上真的太吵了，老外滩酒吧要到凌晨两三点，睡眠不好的慎重！', created_at: '2024-06-20' },
    ]
  },

  {
    id: 'mock-006',
    title: '测试6',
    address: '江北区洪塘中路200号亲亲家园',
    district: '江北区',
    lat: 29.925,
    lng: 121.505,
    area_sqm: 78,
    bedrooms: 2,
    halls: 1,
    description: '江北洪塘亲亲家园，成熟社区。两室一厅，简单装修。适合在江北工业园区上班的租客。楼下公交直达市区，附近有洪塘购物中心。性价比高。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 2, monthly_rent: 1600 },
      { orientation: '南', floor_level: '中层', floor_number: 7, monthly_rent: 1800 },
      { orientation: '北', floor_level: '低层', floor_number: 2, monthly_rent: 1400 },
      { orientation: '北', floor_level: '中层', floor_number: 7, monthly_rent: 1600 },
    ],
    utilities: {
      water_price: 3.2,
      electricity_price: 0.55,
      appliances: [
        { name: '空调（卧室）', energy_level: 4, power_watts: 1200, daily_cost_yuan: 9.6 },
        { name: '热水器', energy_level: 3, power_watts: 2000, daily_cost_yuan: 4.8 },
        { name: '冰箱', energy_level: 3, power_watts: 120, daily_cost_yuan: 1.6 },
        { name: '洗衣机', energy_level: 3, power_watts: 500, daily_cost_yuan: 2.5 },
      ],
      property_fee: 60,
      property_fee_included: true,
      internet_fee: 0,
      internet_fee_included: true,
      parking_fee: 80,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r27', user_name: '老刘', rating: 5, content: '性价比非常高！物业费网费都包了，每个月能省不少。', created_at: '2024-07-16' },
      { id: 'r28', user_name: '阿花', rating: 3, content: '装修旧了点，不过价格确实便宜。电器能耗有点高，电费贵。', created_at: '2024-07-08' },
      { id: 'r29', user_name: '小彭', rating: 4, content: '楼下菜场超市都有，生活方便。公交到市区40分钟。', created_at: '2024-06-25' },
    ]
  },

  {
    id: 'mock-007',
    title: '测试7',
    address: '镇海区庄市街道毓秀路66号',
    district: '镇海区',
    lat: 29.938,
    lng: 121.610,
    area_sqm: 35,
    bedrooms: 1,
    halls: 0,
    description: '宁波大学附近学生公寓，步行5分钟到宁大正门。精装单间带独卫、小阳台。楼下有学生食堂、快递站。适合宁大学生或考研党。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 2, monthly_rent: 1200 },
      { orientation: '南', floor_level: '中层', floor_number: 6, monthly_rent: 1300 },
      { orientation: '北', floor_level: '低层', floor_number: 2, monthly_rent: 1000 },
      { orientation: '北', floor_level: '中层', floor_number: 6, monthly_rent: 1100 },
    ],
    utilities: {
      water_price: 3.2,
      electricity_price: 0.55,
      appliances: [
        { name: '空调', energy_level: 5, power_watts: 900, daily_cost_yuan: 7.2 },
        { name: '热水器', energy_level: 4, power_watts: 1500, daily_cost_yuan: 4.0 },
      ],
      property_fee: 0,
      property_fee_included: true,
      internet_fee: 20,
      internet_fee_included: true,
      parking_fee: 0,
      parking_fee_included: true,
    },
    reviews: [
      { id: 'r30', user_name: '宁大学生小王', rating: 5, content: '离学校近，价格便宜，考研复习的好地方。网速也快。', created_at: '2024-07-19' },
      { id: 'r31', user_name: '考研党小李', rating: 4, content: '周围都是学生，环境单纯。就是空调5级能耗电费太高了。', created_at: '2024-07-10' },
      { id: 'r32', user_name: '小周', rating: 2, content: '冬天没暖气（只有空调），房间有点冷。热水器也老旧。', created_at: '2024-06-28' },
    ]
  },

  {
    id: 'mock-008',
    title: '测试8',
    address: '镇海区骆驼街道慈海南路888号',
    district: '镇海区',
    lat: 29.980,
    lng: 121.590,
    area_sqm: 115,
    bedrooms: 3,
    halls: 2,
    description: '镇海新城核心地段，新交付商品房。三室两厅两卫，南北通透。小区自带底商，对面就是镇海区行政服务中心。适合在镇海工作的家庭。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 3, monthly_rent: 3200 },
      { orientation: '南', floor_level: '中层', floor_number: 11, monthly_rent: 3600 },
      { orientation: '南', floor_level: '高层', floor_number: 20, monthly_rent: 3800 },
      { orientation: '东南', floor_level: '中层', floor_number: 11, monthly_rent: 3500 },
      { orientation: '北', floor_level: '低层', floor_number: 3, monthly_rent: 2800 },
      { orientation: '北', floor_level: '中层', floor_number: 11, monthly_rent: 3200 },
    ],
    utilities: {
      water_price: 3.2,
      electricity_price: 0.55,
      appliances: [
        { name: '空调（卧室×3）', energy_level: 2, power_watts: 1200, daily_cost_yuan: 5.8 },
        { name: '空调（客厅）', energy_level: 2, power_watts: 1800, daily_cost_yuan: 8.6 },
        { name: '热水器', energy_level: 1, power_watts: 2000, daily_cost_yuan: 2.4 },
        { name: '冰箱', energy_level: 1, power_watts: 120, daily_cost_yuan: 1.4 },
        { name: '洗衣机', energy_level: 1, power_watts: 500, daily_cost_yuan: 1.5 },
      ],
      property_fee: 350,
      property_fee_included: false,
      internet_fee: 60,
      internet_fee_included: false,
      parking_fee: 150,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r33', user_name: '镇海老王', rating: 5, content: '新房就是不一样，住着舒服。开发商精装的质量也不错。', created_at: '2024-07-21' },
      { id: 'r34', user_name: '小杨', rating: 4, content: '小区环境好，物业负责。就是目前周边商业还没完全起来。', created_at: '2024-07-12' },
      { id: 'r35', user_name: '陈姐', rating: 5, content: '南北通透夏天很凉快，开空调时间少，电费省了不少。', created_at: '2024-06-30' },
      { id: 'r36', user_name: '大周', rating: 4, content: '相比市区便宜不少，面积也大。通勤到市区开车半小时。', created_at: '2024-06-20' },
    ]
  },

  {
    id: 'mock-009',
    title: '测试9',
    address: '北仑区新碶街道长江路999号',
    district: '北仑区',
    lat: 29.905,
    lng: 121.845,
    area_sqm: 100,
    bedrooms: 2,
    halls: 2,
    description: '北仑核心区域，高层可以看到海。两室两厅带大阳台。楼下就是银泰城，步行到北仑区政府。附近有多条公交线路直达宁波市区。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '中层', floor_number: 15, monthly_rent: 2800 },
      { orientation: '南', floor_level: '高层', floor_number: 28, monthly_rent: 3200 },
      { orientation: '东南', floor_level: '高层', floor_number: 28, monthly_rent: 3500 },
      { orientation: '东', floor_level: '中层', floor_number: 15, monthly_rent: 2600 },
    ],
    utilities: {
      water_price: 3.5,
      electricity_price: 0.6,
      appliances: [
        { name: '空调（卧室）', energy_level: 2, power_watts: 1200, daily_cost_yuan: 5.8 },
        { name: '空调（客厅）', energy_level: 3, power_watts: 1800, daily_cost_yuan: 11.0 },
        { name: '热水器', energy_level: 2, power_watts: 2000, daily_cost_yuan: 3.6 },
        { name: '冰箱', energy_level: 2, power_watts: 110, daily_cost_yuan: 1.3 },
        { name: '洗衣机', energy_level: 1, power_watts: 500, daily_cost_yuan: 1.5 },
      ],
      property_fee: 300,
      property_fee_included: false,
      internet_fee: 60,
      internet_fee_included: true,
      parking_fee: 200,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r37', user_name: '北仑小陈', rating: 5, content: '高层视野真的棒，能看到海。银泰城就在楼下，逛街吃饭都方便。', created_at: '2024-07-20' },
      { id: 'r38', user_name: '阿峰', rating: 4, content: '小区品质不错，就是北仑离市区确实有点远，通勤时间比较长。', created_at: '2024-07-10' },
      { id: 'r39', user_name: '小丽', rating: 5, content: '网费含在租金里，这点很满意。阳台很大可以种花。', created_at: '2024-06-25' },
      { id: 'r40', user_name: '大壮', rating: 2, content: '冬天风太大了，高层特别明显。物业费300性价比不高。', created_at: '2024-06-15' },
    ]
  },

  {
    id: 'mock-010',
    title: '测试10',
    address: '北仑区大碶街道坝头路268号',
    district: '北仑区',
    lat: 29.885,
    lng: 121.805,
    area_sqm: 90,
    bedrooms: 2,
    halls: 1,
    description: '大碶工业园区周边，适合在附近工厂和物流园上班的家庭。多层住宅，无电梯。小区安静，停车方便。附近有大碶菜场和卫生院。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 2, monthly_rent: 1500 },
      { orientation: '南', floor_level: '中层', floor_number: 4, monthly_rent: 1700 },
      { orientation: '北', floor_level: '低层', floor_number: 2, monthly_rent: 1300 },
      { orientation: '北', floor_level: '中层', floor_number: 4, monthly_rent: 1500 },
      { orientation: '东', floor_level: '低层', floor_number: 2, monthly_rent: 1400 },
    ],
    utilities: {
      water_price: 3.0,
      electricity_price: 0.52,
      appliances: [
        { name: '空调', energy_level: 4, power_watts: 1500, daily_cost_yuan: 10.0 },
        { name: '热水器', energy_level: 3, power_watts: 2000, daily_cost_yuan: 5.0 },
        { name: '冰箱', energy_level: 4, power_watts: 130, daily_cost_yuan: 1.8 },
        { name: '洗衣机', energy_level: 3, power_watts: 500, daily_cost_yuan: 2.5 },
      ],
      property_fee: 40,
      property_fee_included: true,
      internet_fee: 0,
      internet_fee_included: true,
      parking_fee: 0,
      parking_fee_included: true,
    },
    reviews: [
      { id: 'r41', user_name: '老工人张', rating: 5, content: '价格实惠，离厂里近，骑着电瓶车5分钟就到。停车也不要钱。', created_at: '2024-07-18' },
      { id: 'r42', user_name: '刘姐', rating: 3, content: '老房子没电梯，搬东西累。电器都比较老，能耗高。', created_at: '2024-07-05' },
      { id: 'r43', user_name: '小徐', rating: 4, content: '虽然设施旧了点，但这个价格真的没什么好挑剔的了。', created_at: '2024-06-22' },
    ]
  },

  {
    id: 'mock-011',
    title: '测试11',
    address: '奉化区锦屏街道中山路168号',
    district: '奉化区',
    lat: 29.655,
    lng: 121.415,
    area_sqm: 82,
    bedrooms: 2,
    halls: 1,
    description: '奉化老城区，周边生活气息浓厚。步行可到奉化江边散步。适合喜欢安静、慢节奏生活的人。距离奉化火车站15分钟车程。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 3, monthly_rent: 1300 },
      { orientation: '南', floor_level: '中层', floor_number: 6, monthly_rent: 1500 },
      { orientation: '北', floor_level: '低层', floor_number: 3, monthly_rent: 1100 },
      { orientation: '北', floor_level: '中层', floor_number: 6, monthly_rent: 1300 },
    ],
    utilities: {
      water_price: 3.0,
      electricity_price: 0.52,
      appliances: [
        { name: '空调', energy_level: 3, power_watts: 1200, daily_cost_yuan: 7.0 },
        { name: '热水器', energy_level: 2, power_watts: 1500, daily_cost_yuan: 2.8 },
        { name: '冰箱', energy_level: 2, power_watts: 100, daily_cost_yuan: 1.1 },
      ],
      property_fee: 50,
      property_fee_included: true,
      internet_fee: 0,
      internet_fee_included: true,
      parking_fee: 0,
      parking_fee_included: true,
    },
    reviews: [
      { id: 'r44', user_name: '奉化老陈', rating: 5, content: '住了两年了，房东从没涨过房租。老城区生活节奏慢，很喜欢。', created_at: '2024-07-17' },
      { id: 'r45', user_name: '阿丽', rating: 4, content: '安静是真的很安静，晚上9点街上就没什么人了。适合喜欢安静的人。', created_at: '2024-07-08' },
      { id: 'r46', user_name: '小方', rating: 2, content: '离宁波市区太远了，通勤不现实。没有洗衣机不太方便。', created_at: '2024-06-28' },
    ]
  },

  {
    id: 'mock-012',
    title: '测试12',
    address: '奉化区岳林街道南山路388号',
    district: '奉化区',
    lat: 29.660,
    lng: 121.425,
    area_sqm: 120,
    bedrooms: 3,
    halls: 2,
    description: '奉化万达广场附近，新建商品房小区，精装交付。三室两厅两卫，电梯房，一梯两户。小区有儿童游乐区和健身设施。适合在奉化安家的家庭。',
    images: [],
    prices: [
      { orientation: '南', floor_level: '低层', floor_number: 5, monthly_rent: 2500 },
      { orientation: '南', floor_level: '中层', floor_number: 12, monthly_rent: 2800 },
      { orientation: '南', floor_level: '高层', floor_number: 22, monthly_rent: 3000 },
      { orientation: '东南', floor_level: '中层', floor_number: 12, monthly_rent: 2700 },
      { orientation: '西南', floor_level: '低层', floor_number: 5, monthly_rent: 2400 },
    ],
    utilities: {
      water_price: 3.2,
      electricity_price: 0.55,
      appliances: [
        { name: '空调（卧室×3）', energy_level: 2, power_watts: 1200, daily_cost_yuan: 5.8 },
        { name: '空调（客厅）', energy_level: 2, power_watts: 1800, daily_cost_yuan: 8.6 },
        { name: '热水器', energy_level: 1, power_watts: 2000, daily_cost_yuan: 2.4 },
        { name: '冰箱', energy_level: 1, power_watts: 120, daily_cost_yuan: 1.4 },
        { name: '洗衣机', energy_level: 1, power_watts: 500, daily_cost_yuan: 1.5 },
      ],
      property_fee: 280,
      property_fee_included: false,
      internet_fee: 50,
      internet_fee_included: true,
      parking_fee: 120,
      parking_fee_included: false,
    },
    reviews: [
      { id: 'r47', user_name: '奉化小张', rating: 5, content: '奉化万达就在隔壁，生活超方便。新房住着就是舒服。', created_at: '2024-07-16' },
      { id: 'r48', user_name: '大刘', rating: 4, content: '物业不错，小区也干净。就是奉化到宁波市区的通勤还是有点远。', created_at: '2024-07-05' },
      { id: 'r49', user_name: '周姐', rating: 5, content: '三个房间都朝南，采光好到爆。空调二级能耗也算省电了。', created_at: '2024-06-25' },
    ]
  },
];

// 兼容字段：为所有 mock 数据添加 status, submitted_by, created_at
MOCK_LISTINGS.forEach(l => {
  if (!l.status) l.status = 'approved';
  if (!l.submitted_by) l.submitted_by = null;
  if (!l.created_at) l.created_at = '2024-07-01';
});

// 如果数据加载成功
console.log(`✅ 已加载 ${MOCK_LISTINGS.length} 条宁波房源示例数据`);
